FROM mzmssg/pai.build.base:hadoop2.7.2-cuda9.0-cudnn7-devel-ubuntu16.04

RUN apt-get -y update && \
    apt-get -y install git \
        fuse \
        golang \
        libjasper1 \
        libjpeg8 \
        libpng12-0 \
        libgfortran3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /

# Install Anaconda
RUN ANACONDA_PREFIX="/root/anaconda3" && \
    ANACONDA_VERSION="3-5.2.0" && \
    wget -q https://repo.continuum.io/archive/Anaconda${ANACONDA_VERSION}-Linux-x86_64.sh && \
    chmod a+x Anaconda${ANACONDA_VERSION}-Linux-x86_64.sh && \
    ./Anaconda${ANACONDA_VERSION}-Linux-x86_64.sh -b -p ${ANACONDA_PREFIX} && \
    rm -rf Anaconda${ANACONDA_VERSION}-Linux-x86_64.sh && \
    $ANACONDA_PREFIX/bin/conda clean --all --yes

ENV PATH=/root/anaconda3/bin:/usr/local/mpi/bin:$PATH \
    LD_LIBRARY_PATH=/root/anaconda3/lib:/usr/local/mpi/lib:$LD_LIBRARY_PATH

# Install tensorflow
RUN pip install tensorflow-gpu && \
    pip install opencv-python

RUN git clone https://github.com/mzmssg/tf_unet.git && \
    cd tf_unet && \
    python setup.py install


WORKDIR /root